/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.CONVERTOR;

/**
 *
 * @author almasfiza
 */
public class Currency extends javax.swing.JFrame {

            
    /**
     * Creates new form Currency
     */
    public Currency() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        inputcurr = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        outputcurr = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        convert = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        Result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Input Currency:");

        inputcurr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "United States Dollar", "Indian Rupee", "Pound Sterling", " " }));
        inputcurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputcurrActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount:");

        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });

        jLabel2.setText("Convert To:");

        outputcurr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "United States Dollar", "Indian Rupee", "Pound Sterling", "Japanesese Yen", "Euro", "Canadian Dollar", "Australian Dollar", "Turkish Lira" }));
        outputcurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputcurrActionPerformed(evt);
            }
        });

        jLabel3.setText("Converted amount:");

        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        Result.setText("-");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jLabel4.setText("Currency Converter");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputcurr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(convert)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Result))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputcurr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputcurr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputcurr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Result))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convert)
                    .addComponent(clear)
                    .addComponent(EXIT))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputcurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputcurrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputcurrActionPerformed

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        // TODO add your handling code here:
        Float.parseFloat(amt.getText());
    }//GEN-LAST:event_amtActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here: 
        double c=0; double a=Double.valueOf(amt.getText());
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==0)
         c=a;
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==1)
         c=a*71.76;// USD to INR
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==2)
         c=a*0.80;//USD to GBP
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==3)
         c=a*108.08;//USD to YEN
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==4)
         c=a*0.91;//USD to EUR
    if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==5)
         c=a*1.33;//USD to CAD
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==6)
         c=a*1.46;//USD to AUD
        if(inputcurr.getSelectedIndex()==0 && outputcurr.getSelectedIndex()==7)
         c=a*5.72;//USD to LIRA
        
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==0)
         c=a/71.76;//INR to USD
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==1)
         c=a;//INR to USD
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==2)
         c=a*0.011;//INR to GBP
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==3)
         c=a*1.51;//INR to YEN
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==4)
         c=a*0.013;//INR to EUR
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==5)
         c=a*0.019;//INR to CAD
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==6)
         c=a*0.020;//INR TO AUD
        if(inputcurr.getSelectedIndex()==1 && outputcurr.getSelectedIndex()==7)
         c=a*0.080;//INR to LIRA
      
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==0)
         c=a/0.81;//GBP to USD
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==1)
         c=a*89.13;//GBP to INR
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==2)
         c=a;
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==3)
         c=a*134.32;//GBP to YEN
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==4)
         c=a*1.13;//GBPto EUR
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==5)
         c=a*1.65;//GBP to CAD
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==6)
         c=a*1.82;//GBP TO AUD
        if(inputcurr.getSelectedIndex()==2 && outputcurr.getSelectedIndex()==7)
         c=a*7.11;//GBP to Lira
        
        double result=c;
      
        //double result=Math.round(c*100.00)/100.0;//rounding off to two decimal
        Result.setText(String.valueOf(result));
        
        
    }//GEN-LAST:event_convertActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        amt.setText(null);
        Result.setText("-");
        
    }//GEN-LAST:event_clearActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        dispose();
        CONVERTER secondframe=new CONVERTER();
        secondframe.setVisible(true);
    }//GEN-LAST:event_EXITActionPerformed

    private void outputcurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputcurrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputcurrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField amt;
    private javax.swing.JButton clear;
    private javax.swing.JButton convert;
    private javax.swing.JComboBox<String> inputcurr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> outputcurr;
    // End of variables declaration//GEN-END:variables
}
